<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <NeutralLanguage>en</NeutralLanguage>
    <AnalysisMode>All</AnalysisMode>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <StaticWebAssetsEnabled>true</StaticWebAssetsEnabled>

    <PackageId>GCFoundation.Components</PackageId>
    <RootNamespace>GCFoundation.Components</RootNamespace>
    <AssemblyName>GCFoundation.Components</AssemblyName>
    <Version>1.0.0</Version>
    <Authors>Philippe G. Vadnais;Shawn Turcotte</Authors>
    <Company>TBS-SCT</Company>
    <Description>Razor components and tag helpers based on the GC Design System (GCDS) for Government of Canada web applications.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/tbs-imtd/GCFoundation</RepositoryUrl>
    <PackageProjectUrl>https://github.com/tbs-imtd/GCFoundation</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IncludeSymbols>true</IncludeSymbols>
    <IncludeSource>true</IncludeSource>
    <PackageTags>GCFoundation;GCDS;GC Design System;Government of Canada;Razor;Components;TagHelpers;ASP.NET;MVC;NET</PackageTags>
    <ErrorLog>Foundation.Components.sarif,version=2.1</ErrorLog>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningsAsErrors>$(WarningsAsErrors);NU1605;</WarningsAsErrors>
    <WarningLevel>8</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningsAsErrors>$(WarningsAsErrors);NU1605;</WarningsAsErrors>
    <WarningLevel>8</WarningLevel>
  </PropertyGroup>

  <Target Name="NpmInstall" BeforeTargets="Build">
    <Exec Command="npm install" WorkingDirectory="$(ProjectDir)" />
  </Target>

  <Target Name="NpmBuild" BeforeTargets="Build" DependsOnTargets="NpmInstall">
    <Exec Command="npm run build" WorkingDirectory="$(ProjectDir)" />
  </Target>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="cloudscribe.Web.Navigation" Version="8.7.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Authentication.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Authentication.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Error.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Error.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Localization.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Localization.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Modal.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Modal.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Stepper.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Stepper.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Validation.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Validation.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Authentication.en.resx">
      <Generator></Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Authentication.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Authentication.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Error.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Error.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Localization.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Localization.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Modal.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Modal.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Stepper.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Stepper.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Validation.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Validation.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <!-- Include all Views in Shared Components -->
    <EmbeddedResource Include="Views\**\*.*" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Converters\**" />
    <Compile Remove="wwwroot\scss\**" />
    <Content Remove="Converters\**" />
    <Content Remove="wwwroot\scss\**" />
    <EmbeddedResource Remove="Converters\**" />
    <EmbeddedResource Remove="wwwroot\scss\**" />
    <None Remove="Converters\**" />
    <None Remove="wwwroot\scss\**" />
  </ItemGroup>
  
  <ItemGroup>
    <Content Remove="package-lock.json" />
    <Content Remove="package.json" />    
    <Content Remove="Views\Shared\_ViewImports.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Views\Shared\Components\Navigation\GCDSBreadcrumbs.cshtml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
	<Content Update="Views\Shared\Components\GCDSTopNavigation.cshtml">
		<CopyToOutputDirectory>Never</CopyToOutputDirectory>
	</Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DataAnnotations\" />
    <Folder Include="wwwroot\images\Icons\" />
    <Folder Include="wwwroot\images\splash\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="package-lock.json" />
    <None Include="package.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GCFoundation.Common\GCFoundation.Common.csproj" />
  </ItemGroup>

  <!-- README for NuGet.org -->
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Views\Language\Index.cshtml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

</Project>
