using Microsoft.AspNetCore.Razor.TagHelpers;

namespace GCFoundation.Components.TagHelpers.GCDS
{
    /// <summary>
    /// A TagHelper that renders a GC Design System breadcrumbs component as a <c>&lt;gcds-breadcrumbs&gt;</c> element.
    /// The breadcrumbs are used for navigation to show the current page's location within the website structure.
    /// </summary>
    /// <example>
    /// <code>
    /// &lt;gcds-breadcrumbs&gt;
    ///     &lt;gcds-breadcrumbs-item href=&quot;/home&quot;&gt;Home&lt;/gcds-breadcrumbs-item&gt;
    /// &lt;/gcds-breadcrumbs&gt;
    /// </code>
    /// </example>
    [HtmlTargetElement("gcds-breadcrumbs")]
    public class BreadcrumbsTagHelper : BaseTagHelper
    {
        /// <summary>
        /// Gets or sets a flag indicating whether to hide the Canada link in the breadcrumbs. Default is <c>false</c>.
        /// </summary>
        public bool HideCanadaLink { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="BreadcrumbsTagHelper"/> class.
        /// </summary>
        public BreadcrumbsTagHelper() { }

        /// <summary>
        /// Processes the <c>gcds-breadcrumbs</c> element by adding the <c>hide-canada-link</c> and <c>lang</c> attributes
        /// to the rendered output. It controls whether the Canada link is shown and the language of the breadcrumbs.
        /// </summary>
        /// <param name="context">The context for the tag helper.</param>
        /// <param name="output">The HTML element output generated by the tag helper.</param>
        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
            AddAttributeIfNotNull(output, "hide-canada-link", HideCanadaLink);
            AddAttributeIfNotNull(output, "lang", Lang);

            base.Process(context, output);
        }
    }
}
