using GCFoundation.Components.Enums;
using Microsoft.AspNetCore.Razor.TagHelpers;

namespace GCFoundation.Components.TagHelpers.GCDS
{
    /// <summary>
    /// A TagHelper that renders a GC Design System header component as a <c>&lt;gcds-header&gt;</c> element.
    /// The header component typically includes a language toggle, skip-to-content link, and a signature, along with other header-related elements.
    /// </summary>
    /// <example>
    /// <code>
    /// &lt;gcds-header lang-href=&quot;/fr&quot; skip-to-href=&quot;#main&quot; signature-has-link=&quot;true&quot;&gt;&lt;/gcds-header&gt;
    /// </code>
    /// </example>
    [HtmlTargetElement("gcds-header")]
    public class HeaderTagHelper : BaseTagHelper
    {
        /// <summary>
        /// Gets or sets the URL for the language toggle link. This is typically used for switching between languages.
        /// </summary>
        public required string LangHref { get; set; }

        /// <summary>
        /// Gets or sets the URL for the "skip to content" link. This allows users to quickly jump to the main content of the page.
        /// </summary>
        public required string SkipToHref { get; set; }

        /// <summary>
        /// Gets or sets a flag indicating whether the signature has a link. Default is <c>true</c>.
        /// </summary>
        public bool SignatureHasLink { get; set; } = true;

        /// <summary>
        /// Gets or sets the variant of the header signature. The default is <see cref="HeaderSignatureVariant.colour"/>.
        /// GCDS v1 removed the <c>signature-variant</c> attribute from <c>gcds-header</c>; this property is retained for compatibility but is not rendered.
        /// </summary>
        [Obsolete("GCDS v1 no longer supports signature-variant on gcds-header; this value is ignored.")]
        public HeaderSignatureVariant SignatureVariant { get; set; } = HeaderSignatureVariant.colour;

        /// <summary>
        /// Processes the <c>gcds-header</c> element by adding the <c>lang-href</c>, <c>skip-to-href</c>, <c>lang</c>, and <c>signature-has-link</c> attributes to the rendered output.
        /// </summary>
        /// <param name="context">The context for the tag helper.</param>
        /// <param name="output">The HTML element output generated by the tag helper.</param>
        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
            AddAttributeIfNotNull(output, "lang-href", LangHref);
            AddAttributeIfNotNull(output, "skip-to-href", SkipToHref);
            AddAttributeIfNotNull(output, "lang", Lang);
            AddAttributeIfNotNull(output, "signature-has-link", SignatureHasLink);

            base.Process(context, output);
        }
    }
}
