using Microsoft.AspNetCore.Razor.TagHelpers;

namespace GCFoundation.Components.TagHelpers.GCDS
{
    /// <summary>
    /// A TagHelper that renders a GC Design System side navigation component as a <c>&lt;gcds-side-nav&gt;</c> element.
    /// The side navigation is typically used for displaying a list of navigation links on the side of the page.
    /// </summary>
    /// <example>
    /// <code>
    /// &lt;gcds-side-nav label=&quot;Section&quot;&gt;
    ///     &lt;gcds-nav-link href=&quot;/apply&quot;&gt;Apply&lt;/gcds-nav-link&gt;
    /// &lt;/gcds-side-nav&gt;
    /// </code>
    /// </example>
    [HtmlTargetElement("gcds-side-nav")]
    public class SideNavigationTagHelper : BaseTagHelper
    {
        /// <summary>
        /// Gets or sets the label for the side navigation. This is usually displayed as the navigation header.
        /// </summary>
        public required string Label { get; set; }

        /// <summary>
        /// Processes the <c>gcds-side-nav</c> element by adding the <c>label</c> and <c>lang</c> attributes to the rendered output.
        /// </summary>
        /// <param name="context">The context for the tag helper.</param>
        /// <param name="output">The HTML element output generated by the tag helper.</param>
        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
            AddAttributeIfNotNull(output, "label", Label);
            AddAttributeIfNotNull(output, "lang", Lang);
            base.Process(context, output);
        }
    }
}
