using GCFoundation.Components.Enums;
using Microsoft.AspNetCore.Razor.TagHelpers;

namespace GCFoundation.Components.TagHelpers.GCDS
{
    /// <summary>
    /// A TagHelper that renders a GC Design System stepper component as a <c>&lt;gcds-stepper&gt;</c> element.
    /// Used to indicate the user's progress through a sequence of steps.
    /// </summary>
    /// <example>
    /// <code>
    /// &lt;gcds-stepper current-step=&quot;2&quot; total-step=&quot;5&quot; tag=&quot;h2&quot;&gt;
    ///     Contact information
    /// &lt;/gcds-stepper&gt;
    /// </code>
    /// </example>
    [HtmlTargetElement("gcds-stepper")]
    public class StepperTagHelper : BaseTagHelper
    {
        /// <summary>
        /// Gets or sets the current step in the sequence. Should be a 1-based index.
        /// </summary>
        public int CurrentStep { get; set; }

        /// <summary>
        /// Gets or sets the total number of steps in the sequence.
        /// </summary>
        public int TotalStep { get; set; }

        /// <summary>
        /// Gets or sets the HTML tag to use for the stepper heading.
        /// Default is <see cref="StepperTag.h2"/>.
        /// </summary>
        public StepperTag Tag { get; set; } = StepperTag.h2;

        /// <summary>
        /// Processes the <c>gcds-stepper</c> element by adding the <c>current-step</c>, <c>total-step</c>,
        /// <c>lang</c>, and <c>tag</c> attributes to the rendered output.
        /// </summary>
        /// <param name="context">The context for the tag helper.</param>
        /// <param name="output">The HTML element output generated by the tag helper.</param>
        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
            AddAttributeIfNotNull(output, "current-step", CurrentStep);
            AddAttributeIfNotNull(output, "total-step", TotalStep);
            AddAttributeIfNotNull(output, "current-step", Lang);
            AddAttributeIfNotNull(output, "tag", Tag);
            base.Process(context, output);
        }
    }
}
