using System.Diagnostics.CodeAnalysis;
using Microsoft.AspNetCore.Razor.TagHelpers;

namespace GCFoundation.Components.TagHelpers.GCDS
{
    /// <summary>
    /// A TagHelper that renders a GC Design System language toggle component as a <c>&lt;gcds-lang-toggle&gt;</c> element.
    /// Adds the target language and URL as attributes.
    /// </summary>
    [HtmlTargetElement("gcds-lang-toggle")]
    public class ToggleLanguageTagHelper : BaseTagHelper
    {
        /// <summary>
        /// Gets or sets the hyperlink reference for the language toggle.
        /// This should point to the alternate-language version of the current page.
        /// </summary>
        [StringSyntax(StringSyntaxAttribute.Uri)]
        public required string Href { get; set; }

        /// <summary>
        /// Processes the <c>gcds-lang-toggle</c> element by adding the <c>href</c> and <c>lang</c> attributes to the output.
        /// </summary>
        /// <param name="context">The context for the tag helper.</param>
        /// <param name="output">The HTML element output generated by the tag helper.</param>
        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
            AddAttributeIfNotNull(output, "href", Href);
            AddAttributeIfNotNull(output, "lang", Lang);
            base.Process(context, output);
        }
    }
}
