using GCFoundation.Components.Enums;
using Microsoft.AspNetCore.Razor.TagHelpers;

namespace GCFoundation.Components.TagHelpers.GCDS
{
    /// <summary>
    /// A TagHelper that renders a GC Design System top navigation bar as a <c>&lt;gcds-top-nav&gt;</c> element.
    /// Supports setting a label, alignment, and language attributes.
    /// </summary>
    /// <example>
    /// <code>
    /// &lt;gcds-top-nav label=&quot;Main menu&quot; alignment=&quot;end&quot;&gt;
    ///     &lt;gcds-nav-link href=&quot;/home&quot;&gt;Home&lt;/gcds-nav-link&gt;
    /// &lt;/gcds-top-nav&gt;
    /// </code>
    /// </example>
    [HtmlTargetElement("gcds-top-nav")]
    public class TopNavigationTagHelper : BaseTagHelper
    {
        /// <summary>
        /// Gets or sets the accessible label for the top navigation.
        /// This is typically used by screen readers to describe the purpose of the navigation bar.
        /// </summary>
        public required string Label { get; set; }

        /// <summary>
        /// Gets or sets the alignment of the top menu.
        /// Default is <see cref="TopMenuAlignment.end"/> (legacy <c>right</c>).
        /// </summary>
        public TopMenuAlignment Alignment { get; set; } = TopMenuAlignment.end;

        /// <summary>
        /// Processes the <c>gcds-top-nav</c> element by adding the <c>label</c>, <c>alignment</c>,
        /// and <c>lang</c> attributes to the rendered output.
        /// </summary>
        /// <param name="context">The context for the tag helper.</param>
        /// <param name="output">The HTML element output generated by the tag helper.</param>
        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
            AddAttributeIfNotNull(output, "label", Label);
            AddAttributeIfNotNull(output, "alignment", Alignment);
            AddAttributeIfNotNull(output, "lang", Lang);

            base.Process(context, output);
        }
    }
}
