<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AnalysisMode>All</AnalysisMode>
    <NeutralLanguage>en</NeutralLanguage>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>GCFoundation.Web</RootNamespace>
    <AssemblyName>GCFoundation.Web</AssemblyName>
	  <ErrorLog>$(OutputPath)Foundation.Web.sarif</ErrorLog>
    <NoWarn>$(NoWarn);CA1515</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Infrastructure\Middleware\**" />
    <Compile Remove="Infrastructure\Services\**" />
    <Content Remove="Infrastructure\Middleware\**" />
    <Content Remove="Infrastructure\Services\**" />
    <EmbeddedResource Remove="Infrastructure\Middleware\**" />
    <EmbeddedResource Remove="Infrastructure\Services\**" />
    <None Remove="Infrastructure\Middleware\**" />
    <None Remove="Infrastructure\Services\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="cloudscribe.Web.Localization" Version="8.7.0" />
    <PackageReference Include="cloudscribe.Web.Navigation" Version="8.7.0" />
    <PackageReference Include="cloudscribe.Web.SiteMap" Version="8.7.0" />
    <PackageReference Include="cloudscribe.Web.SiteMap.FromNavigation" Version="8.7.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="RouteLocalization.AspNetCore" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GCFoundation.Common\GCFoundation.Common.csproj" />
    <ProjectReference Include="..\GCFoundation.Components\GCFoundation.Components.csproj" />
    <ProjectReference Include="..\GCFoundation.Security\GCFoundation.Security.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Components.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Components.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Installation.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Installation.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Home.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Home.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Menu.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Menu.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Navigation.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Navigation.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Routes.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Routes.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Template.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Template.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Components.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Components.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Installation.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Installation.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Home.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Home.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Menu.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Menu.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Navigation.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Navigation.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Routes.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Routes.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Template.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Template.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="navigation.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
