//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCFoundation.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Installation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Installation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GCFoundation.Web.Resources.Installation", typeof(Installation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;code&gt;&amp;lt;gcds-date-modified&amp;gt;&lt;/code&gt; displayed in the shared layout (&lt;code&gt;_FoundationLayout.cshtml&lt;/code&gt;) renders one of two values:.
        /// </summary>
        public static string DateModified_Intro {
            get {
                return ResourceManager.GetString("DateModified_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Date modified&lt;/strong&gt;: Developers can use the &lt;code&gt;SetDateModified(DateTime dateModified)&lt;/code&gt; method of the &lt;code&gt;GCFoundationBaseController&lt;/code&gt; to set the value of &lt;code&gt;ViewData[&quot;DateModified&quot;]&lt;/code&gt;. Date modified takes precedence over the application version number. (recommended ISO format &lt;code&gt;yyyy-MM-dd&lt;/code&gt;).
        /// </summary>
        public static string DateModified_Item_Date {
            get {
                return ResourceManager.GetString("DateModified_Item_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Version&lt;/strong&gt;: For web applications, developers can configure the &lt;code&gt;ApplicationVersion&lt;/code&gt; property within the &lt;code&gt;FoundationComponentsSettings&lt;/code&gt; section of the &lt;code&gt;appsettings.json&lt;/code&gt; file..
        /// </summary>
        public static string DateModified_Item_Version {
            get {
                return ResourceManager.GetString("DateModified_Item_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information about the &lt;code&gt;&amp;lt;gcds-date-modified&amp;gt;&lt;/code&gt; tag, please take a look at the &lt;gcds-link href=&quot;https://design-system.alpha.canada.ca/en/components/date-modified/&quot; target=&quot;_blank&quot; external&gt;GC Design System documentation&lt;/gcds-link&gt;..
        /// </summary>
        public static string DateModified_Link {
            get {
                return ResourceManager.GetString("DateModified_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date modified/Version number.
        /// </summary>
        public static string DateModified_Page_Title {
            get {
                return ResourceManager.GetString("DateModified_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Enabled.
        /// </summary>
        public static string GlobalResources_AlwaysEnabled {
            get {
                return ResourceManager.GetString("GlobalResources_AlwaysEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS Loading Order.
        /// </summary>
        public static string GlobalResources_CssLoadingOrder_Title {
            get {
                return ResourceManager.GetString("GlobalResources_CssLoadingOrder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following resources are currently configured to be loaded globally:.
        /// </summary>
        public static string GlobalResources_CurrentConfiguration_Description {
            get {
                return ResourceManager.GetString("GlobalResources_CurrentConfiguration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Configuration.
        /// </summary>
        public static string GlobalResources_CurrentConfiguration_Title {
            get {
                return ResourceManager.GetString("GlobalResources_CurrentConfiguration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default CSS:.
        /// </summary>
        public static string GlobalResources_DefaultCss_Label {
            get {
                return ResourceManager.GetString("GlobalResources_DefaultCss_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Note:&lt;/strong&gt; Default foundation CSS and JavaScript files are always included and cannot be disabled. This ensures that all GCFoundation components work properly on every page..
        /// </summary>
        public static string GlobalResources_DefaultFilesNote {
            get {
                return ResourceManager.GetString("GlobalResources_DefaultFilesNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default JavaScript:.
        /// </summary>
        public static string GlobalResources_DefaultJavaScript_Label {
            get {
                return ResourceManager.GetString("GlobalResources_DefaultJavaScript_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page demonstrates how to use the new global resources configuration feature in GCFoundation. You can configure CSS, JavaScript, meta tags, and link tags globally through the appsettings.json file..
        /// </summary>
        public static string GlobalResources_Description {
            get {
                return ResourceManager.GetString("GlobalResources_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Awesome:.
        /// </summary>
        public static string GlobalResources_FontAwesome_Label {
            get {
                return ResourceManager.GetString("GlobalResources_FontAwesome_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCDS Resources:.
        /// </summary>
        public static string GlobalResources_GCDSResources_Label {
            get {
                return ResourceManager.GetString("GlobalResources_GCDSResources_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global CSS Files.
        /// </summary>
        public static string GlobalResources_GlobalCssFiles_Title {
            get {
                return ResourceManager.GetString("GlobalResources_GlobalCssFiles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global JavaScript Files.
        /// </summary>
        public static string GlobalResources_GlobalJavaScriptFiles_Title {
            get {
                return ResourceManager.GetString("GlobalResources_GlobalJavaScriptFiles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Link Tags.
        /// </summary>
        public static string GlobalResources_GlobalLinkTags_Title {
            get {
                return ResourceManager.GetString("GlobalResources_GlobalLinkTags_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Meta Tags.
        /// </summary>
        public static string GlobalResources_GlobalMetaTags_Title {
            get {
                return ResourceManager.GetString("GlobalResources_GlobalMetaTags_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To configure global resources, update your &lt;code&gt;appsettings.json&lt;/code&gt; file:.
        /// </summary>
        public static string GlobalResources_HowToConfigure_Description {
            get {
                return ResourceManager.GetString("GlobalResources_HowToConfigure_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Configure.
        /// </summary>
        public static string GlobalResources_HowToConfigure_Title {
            get {
                return ResourceManager.GetString("GlobalResources_HowToConfigure_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScript Loading Order.
        /// </summary>
        public static string GlobalResources_JavaScriptLoadingOrder_Title {
            get {
                return ResourceManager.GetString("GlobalResources_JavaScriptLoadingOrder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources are loaded in the following order:.
        /// </summary>
        public static string GlobalResources_LoadingOrder_Description {
            get {
                return ResourceManager.GetString("GlobalResources_LoadingOrder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Loading Order.
        /// </summary>
        public static string GlobalResources_LoadingOrder_Title {
            get {
                return ResourceManager.GetString("GlobalResources_LoadingOrder_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No global CSS files configured..
        /// </summary>
        public static string GlobalResources_NoCssFiles {
            get {
                return ResourceManager.GetString("GlobalResources_NoCssFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No global JavaScript files configured..
        /// </summary>
        public static string GlobalResources_NoJavaScriptFiles {
            get {
                return ResourceManager.GetString("GlobalResources_NoJavaScriptFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No global link tags configured..
        /// </summary>
        public static string GlobalResources_NoLinkTags {
            get {
                return ResourceManager.GetString("GlobalResources_NoLinkTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No global meta tags configured..
        /// </summary>
        public static string GlobalResources_NoMetaTags {
            get {
                return ResourceManager.GetString("GlobalResources_NoMetaTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Resources.
        /// </summary>
        public static string GlobalResources_Page_Title {
            get {
                return ResourceManager.GetString("GlobalResources_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following settings control which optional resources are included:.
        /// </summary>
        public static string GlobalResources_ResourceInclusion_Description {
            get {
                return ResourceManager.GetString("GlobalResources_ResourceInclusion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Inclusion Settings.
        /// </summary>
        public static string GlobalResources_ResourceInclusion_Title {
            get {
                return ResourceManager.GetString("GlobalResources_ResourceInclusion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also use the &lt;code&gt;GlobalResourceHelper&lt;/code&gt; in your Razor views for more control:.
        /// </summary>
        public static string GlobalResources_UsingHelper_Description {
            get {
                return ResourceManager.GetString("GlobalResources_UsingHelper_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using GlobalResourceHelper in Views.
        /// </summary>
        public static string GlobalResources_UsingHelper_Title {
            get {
                return ResourceManager.GetString("GlobalResources_UsingHelper_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Setup.
        /// </summary>
        public static string Index_BasicSetup_Heading {
            get {
                return ResourceManager.GetString("Index_BasicSetup_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the following services in your &lt;code&gt;Program.cs&lt;/code&gt;:.
        /// </summary>
        public static string Index_BasicSetup_Intro {
            get {
                return ResourceManager.GetString("Index_BasicSetup_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breadcrumbs Setup.
        /// </summary>
        public static string Index_BreadcrumbsSetup_Heading {
            get {
                return ResourceManager.GetString("Index_BreadcrumbsSetup_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure navigation and breadcrumbs services in &lt;code&gt;Program.cs&lt;/code&gt;:.
        /// </summary>
        public static string Index_BreadcrumbsSetup_Intro {
            get {
                return ResourceManager.GetString("Index_BreadcrumbsSetup_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add GCFoundation Content Security Policy (CSP).
        /// </summary>
        public static string Index_CodeComment_AddContentSecurityPolicy {
            get {
                return ResourceManager.GetString("Index_CodeComment_AddContentSecurityPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddCustomRouteLocalization.
        /// </summary>
        public static string Index_CodeComment_AddCustomRouteLocalization {
            get {
                return ResourceManager.GetString("Index_CodeComment_AddCustomRouteLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add GCFoundation language middleware.
        /// </summary>
        public static string Index_CodeComment_AddLanguageMiddleware {
            get {
                return ResourceManager.GetString("Index_CodeComment_AddLanguageMiddleware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add route localization (translated URLs).
        /// </summary>
        public static string Index_CodeComment_AddRouteLocalization {
            get {
                return ResourceManager.GetString("Index_CodeComment_AddRouteLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add route localization extensions (translated routes).
        /// </summary>
        public static string Index_CodeComment_AddRouteLocalizationExtensions {
            get {
                return ResourceManager.GetString("Index_CodeComment_AddRouteLocalizationExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization and routing.
        /// </summary>
        public static string Index_CodeComment_AuthorizationAndRouting {
            get {
                return ResourceManager.GetString("Index_CodeComment_AuthorizationAndRouting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind navigation visibility rules from configuration.
        /// </summary>
        public static string Index_CodeComment_BindNavigationRules {
            get {
                return ResourceManager.GetString("Index_CodeComment_BindNavigationRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure breadcrumbs localization service.
        /// </summary>
        public static string Index_CodeComment_ConfigureBreadcrumbsLocalization {
            get {
                return ResourceManager.GetString("Index_CodeComment_ConfigureBreadcrumbsLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure default route with culture parameter.
        /// </summary>
        public static string Index_CodeComment_ConfigureDefaultRoute {
            get {
                return ResourceManager.GetString("Index_CodeComment_ConfigureDefaultRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure global resources (resx).
        /// </summary>
        public static string Index_CodeComment_ConfigureGlobalResources {
            get {
                return ResourceManager.GetString("Index_CodeComment_ConfigureGlobalResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure navigation services.
        /// </summary>
        public static string Index_CodeComment_ConfigureNavigationServices {
            get {
                return ResourceManager.GetString("Index_CodeComment_ConfigureNavigationServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure secure cookies.
        /// </summary>
        public static string Index_CodeComment_ConfigureSecureCookies {
            get {
                return ResourceManager.GetString("Index_CodeComment_ConfigureSecureCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure supported cultures (e.g., en-CA, fr-CA).
        /// </summary>
        public static string Index_CodeComment_ConfigureSupportedCultures {
            get {
                return ResourceManager.GetString("Index_CodeComment_ConfigureSupportedCultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure top navigation localization service.
        /// </summary>
        public static string Index_CodeComment_ConfigureTopNavigationLocalization {
            get {
                return ResourceManager.GetString("Index_CodeComment_ConfigureTopNavigationLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture and URL-based localization.
        /// </summary>
        public static string Index_CodeComment_CultureAndUrlLocalization {
            get {
                return ResourceManager.GetString("Index_CodeComment_CultureAndUrlLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable ASP.NET Core request localization.
        /// </summary>
        public static string Index_CodeComment_EnableRequestLocalization {
            get {
                return ResourceManager.GetString("Index_CodeComment_EnableRequestLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error handling (production).
        /// </summary>
        public static string Index_CodeComment_ErrorHandlingProduction {
            get {
                return ResourceManager.GetString("Index_CodeComment_ErrorHandlingProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate rules against the current request (cookie, session, or claim).
        /// </summary>
        public static string Index_CodeComment_EvaluateNavigationRules {
            get {
                return ResourceManager.GetString("Index_CodeComment_EvaluateNavigationRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCFoundation components and security.
        /// </summary>
        public static string Index_CodeComment_GCFoundationComponentsAndSecurity {
            get {
                return ResourceManager.GetString("Index_CodeComment_GCFoundationComponentsAndSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCFoundation services.
        /// </summary>
        public static string Index_CodeComment_GCFoundationServices {
            get {
                return ResourceManager.GetString("Index_CodeComment_GCFoundationServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global resources and localization.
        /// </summary>
        public static string Index_CodeComment_GlobalResourcesAndLocalization {
            get {
                return ResourceManager.GetString("Index_CodeComment_GlobalResourcesAndLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load GCFoundation components and GCDS dependencies.
        /// </summary>
        public static string Index_CodeComment_LoadComponents {
            get {
                return ResourceManager.GetString("Index_CodeComment_LoadComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MVC with localization support.
        /// </summary>
        public static string Index_CodeComment_MvcLocalization {
            get {
                return ResourceManager.GetString("Index_CodeComment_MvcLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation and breadcrumbs.
        /// </summary>
        public static string Index_CodeComment_NavigationAndBreadcrumbs {
            get {
                return ResourceManager.GetString("Index_CodeComment_NavigationAndBreadcrumbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional: localized top navigation labels.
        /// </summary>
        public static string Index_CodeComment_OptionalLocalizedTopNavigation {
            get {
                return ResourceManager.GetString("Index_CodeComment_OptionalLocalizedTopNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register GCFoundation services.
        /// </summary>
        public static string Index_CodeComment_RegisterGCFoundationServices {
            get {
                return ResourceManager.GetString("Index_CodeComment_RegisterGCFoundationServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request localization.
        /// </summary>
        public static string Index_CodeComment_RequestLocalization {
            get {
                return ResourceManager.GetString("Index_CodeComment_RequestLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security and static files.
        /// </summary>
        public static string Index_CodeComment_SecurityAndStaticFiles {
            get {
                return ResourceManager.GetString("Index_CodeComment_SecurityAndStaticFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shown everywhere (topnav, breadcrumbs, sidenav).
        /// </summary>
        public static string Index_CodeComment_ShownEverywhere {
            get {
                return ResourceManager.GetString("Index_CodeComment_ShownEverywhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top nav only.
        /// </summary>
        public static string Index_CodeComment_TopNavigationOnly {
            get {
                return ResourceManager.GetString("Index_CodeComment_TopNavigationOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required &lt;code&gt;appsettings.json&lt;/code&gt; configuration:.
        /// </summary>
        public static string Index_CompleteExample_AppSettings_Intro {
            get {
                return ResourceManager.GetString("Index_CompleteExample_AppSettings_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Program.cs Example.
        /// </summary>
        public static string Index_CompleteExample_Heading {
            get {
                return ResourceManager.GetString("Index_CompleteExample_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s a complete &lt;code&gt;Program.cs&lt;/code&gt; configuration that ties all of the above together for a typical MVC application:.
        /// </summary>
        public static string Index_CompleteExample_Intro {
            get {
                return ResourceManager.GetString("Index_CompleteExample_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example project structure for navigation resources:.
        /// </summary>
        public static string Index_CompleteExample_ProjectStructure_Intro {
            get {
                return ResourceManager.GetString("Index_CompleteExample_ProjectStructure_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components Setup.
        /// </summary>
        public static string Index_ComponentsSetup_Heading {
            get {
                return ResourceManager.GetString("Index_ComponentsSetup_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable GCFoundation components and session middleware in &lt;code&gt;Program.cs&lt;/code&gt;:.
        /// </summary>
        public static string Index_ComponentsSetup_Intro {
            get {
                return ResourceManager.GetString("Index_ComponentsSetup_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied!.
        /// </summary>
        public static string Index_CopyButton_SuccessText {
            get {
                return ResourceManager.GetString("Index_CopyButton_SuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Index_CopyButton_Text {
            get {
                return ResourceManager.GetString("Index_CopyButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure localization, global resources, and culture selection in &lt;code&gt;Program.cs&lt;/code&gt;:.
        /// </summary>
        public static string Index_LanguageSetup_Configuration_Intro {
            get {
                return ResourceManager.GetString("Index_LanguageSetup_Configuration_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Setup.
        /// </summary>
        public static string Index_LanguageSetup_Heading {
            get {
                return ResourceManager.GetString("Index_LanguageSetup_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable language and localization middleware:.
        /// </summary>
        public static string Index_LanguageSetup_Middleware_Intro {
            get {
                return ResourceManager.GetString("Index_LanguageSetup_Middleware_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Visibility.
        /// </summary>
        public static string Index_MenuComponentVisibility_Heading {
            get {
                return ResourceManager.GetString("Index_MenuComponentVisibility_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each node in &lt;code&gt;navigation.xml&lt;/code&gt; can declare which navigation surfaces it appears on using the &lt;code&gt;componentVisibility&lt;/code&gt; attribute. Omitting it entirely means the node is shown in all surfaces by default..
        /// </summary>
        public static string Index_MenuComponentVisibility_Intro {
            get {
                return ResourceManager.GetString("Index_MenuComponentVisibility_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customizable Visibility Restrictions.
        /// </summary>
        public static string Index_MenuRestrictions_Heading {
            get {
                return ResourceManager.GetString("Index_MenuRestrictions_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then register the rules and the permission resolver in &lt;code&gt;Program.cs&lt;/code&gt;:.
        /// </summary>
        public static string Index_MenuRestrictions_Program_Intro {
            get {
                return ResourceManager.GetString("Index_MenuRestrictions_Program_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation nodes can be conditionally shown or hidden based on cookies, session values, or claims. Define rules in &lt;code&gt;appsettings.json&lt;/code&gt; using the nav node key as the rule key:.
        /// </summary>
        public static string Index_MenuRestrictions_Rules_Intro {
            get {
                return ResourceManager.GetString("Index_MenuRestrictions_Rules_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Setup.
        /// </summary>
        public static string Index_MenuSetup_Heading {
            get {
                return ResourceManager.GetString("Index_MenuSetup_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want the top navigation to display localized labels dynamically, register the top navigation localization service in &lt;code&gt;Program.cs&lt;/code&gt;:.
        /// </summary>
        public static string Index_MenuSetup_Intro {
            get {
                return ResourceManager.GetString("Index_MenuSetup_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet Configuration.
        /// </summary>
        public static string Index_NuGetConfiguration_Heading {
            get {
                return ResourceManager.GetString("Index_NuGetConfiguration_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCFoundation packages are published on nuget.org and can be installed directly using the &lt;code&gt;dotnet&lt;/code&gt; CLI or the Visual Studio Package Manager Console..
        /// </summary>
        public static string Index_NuGetConfiguration_Intro {
            get {
                return ResourceManager.GetString("Index_NuGetConfiguration_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string Index_Optional_Badge {
            get {
                return ResourceManager.GetString("Index_Optional_Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the following core NuGet packages (using the &lt;code&gt;dotnet&lt;/code&gt; CLI):.
        /// </summary>
        public static string Index_PackageInstallation_CorePackages_Intro {
            get {
                return ResourceManager.GetString("Index_PackageInstallation_CorePackages_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Installation.
        /// </summary>
        public static string Index_PackageInstallation_Heading {
            get {
                return ResourceManager.GetString("Index_PackageInstallation_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For navigation, breadcrumbs, and URL translation support, install:.
        /// </summary>
        public static string Index_PackageInstallation_NavigationPackages_Intro {
            get {
                return ResourceManager.GetString("Index_PackageInstallation_NavigationPackages_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you prefer the Visual Studio Package Manager Console, you can use:.
        /// </summary>
        public static string Index_PackageInstallation_PackageManager_Intro {
            get {
                return ResourceManager.GetString("Index_PackageInstallation_PackageManager_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation.
        /// </summary>
        public static string Index_Page_Title {
            get {
                return ResourceManager.GetString("Index_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerequisites.
        /// </summary>
        public static string Index_Prerequisites_Heading {
            get {
                return ResourceManager.GetString("Index_Prerequisites_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET Core 10.0 or later.
        /// </summary>
        public static string Index_Prerequisites_Item_AspNetCore {
            get {
                return ResourceManager.GetString("Index_Prerequisites_Item_AspNetCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio 2022 or later.
        /// </summary>
        public static string Index_Prerequisites_Item_VisualStudio {
            get {
                return ResourceManager.GetString("Index_Prerequisites_Item_VisualStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Setup.
        /// </summary>
        public static string Index_SecuritySetup_Heading {
            get {
                return ResourceManager.GetString("Index_SecuritySetup_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add GCFoundation security policies and secure cookie configuration:.
        /// </summary>
        public static string Index_SecuritySetup_Intro {
            get {
                return ResourceManager.GetString("Index_SecuritySetup_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On this page.
        /// </summary>
        public static string Index_SideNav_OnThisPage {
            get {
                return ResourceManager.GetString("Index_SideNav_OnThisPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure &lt;code&gt;appsettings.json&lt;/code&gt; for navigation and global resources:.
        /// </summary>
        public static string Index_UrlTranslation_AppSettings_Intro {
            get {
                return ResourceManager.GetString("Index_UrlTranslation_AppSettings_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Translation.
        /// </summary>
        public static string Index_UrlTranslation_Heading {
            get {
                return ResourceManager.GetString("Index_UrlTranslation_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key features:.
        /// </summary>
        public static string Index_UrlTranslation_KeyFeatures_Heading {
            get {
                return ResourceManager.GetString("Index_UrlTranslation_KeyFeatures_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic breadcrumb localization using resource files.
        /// </summary>
        public static string Index_UrlTranslation_KeyFeatures_Item_BreadcrumbLocalization {
            get {
                return ResourceManager.GetString("Index_UrlTranslation_KeyFeatures_Item_BreadcrumbLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL-based culture selection using the first segment (e.g., &lt;code&gt;/fr/home&lt;/code&gt;).
        /// </summary>
        public static string Index_UrlTranslation_KeyFeatures_Item_CultureSegment {
            get {
                return ResourceManager.GetString("Index_UrlTranslation_KeyFeatures_Item_CultureSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default culture is &lt;code&gt;en-CA&lt;/code&gt;.
        /// </summary>
        public static string Index_UrlTranslation_KeyFeatures_Item_DefaultCulture {
            get {
                return ResourceManager.GetString("Index_UrlTranslation_KeyFeatures_Item_DefaultCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support for culture-specific routing and translated routes using &lt;code&gt;RouteLocalization.AspNetCore&lt;/code&gt;.
        /// </summary>
        public static string Index_UrlTranslation_KeyFeatures_Item_RouteLocalization {
            get {
                return ResourceManager.GetString("Index_UrlTranslation_KeyFeatures_Item_RouteLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure routing with a culture parameter and translated URLs:.
        /// </summary>
        public static string Index_UrlTranslation_Routing_Intro {
            get {
                return ResourceManager.GetString("Index_UrlTranslation_Routing_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior and rules.
        /// </summary>
        public static string Metadata_Behavior_Heading {
            get {
                return ResourceManager.GetString("Metadata_Behavior_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Attributes&lt;/strong&gt;: Use either Name or Property (not both). Charset is standalone; HttpEquiv generally pairs with Content..
        /// </summary>
        public static string Metadata_Behavior_Item_Attributes {
            get {
                return ResourceManager.GetString("Metadata_Behavior_Item_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;De-duplication&lt;/strong&gt;: A tag with the same Name or Property replaces the previous one. Global tags are only added if not already present..
        /// </summary>
        public static string Metadata_Behavior_Item_Dedup {
            get {
                return ResourceManager.GetString("Metadata_Behavior_Item_Dedup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Encoding&lt;/strong&gt;: Attributes are HTML-encoded on render..
        /// </summary>
        public static string Metadata_Behavior_Item_Encoding {
            get {
                return ResourceManager.GetString("Metadata_Behavior_Item_Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Localized content&lt;/strong&gt;: Optional &lt;code&gt;contentEn&lt;/code&gt; and &lt;code&gt;contentFr&lt;/code&gt; are chosen from &lt;code&gt;CurrentUICulture&lt;/code&gt; when rendering; &lt;code&gt;content&lt;/code&gt; is the fallback and suits language-neutral values (for example charset, &lt;code&gt;og:type&lt;/code&gt;)..
        /// </summary>
        public static string Metadata_Behavior_Item_LocalizedContent {
            get {
                return ResourceManager.GetString("Metadata_Behavior_Item_LocalizedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;No view changes needed&lt;/strong&gt;: The layout picks up ViewData[&quot;MetaTags&quot;] automatically..
        /// </summary>
        public static string Metadata_Behavior_Item_NoViewChanges {
            get {
                return ResourceManager.GetString("Metadata_Behavior_Item_NoViewChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Render order&lt;/strong&gt;: Controller tags render first, then non-duplicated global tags..
        /// </summary>
        public static string Metadata_Behavior_Item_Order {
            get {
                return ResourceManager.GetString("Metadata_Behavior_Item_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Metadata_Configuration_Heading {
            get {
                return ResourceManager.GetString("Metadata_Configuration_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set global, always-on meta tags in appsettings.json using the typed MetaTag structure:.
        /// </summary>
        public static string Metadata_Configuration_Intro {
            get {
                return ResourceManager.GetString("Metadata_Configuration_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page demonstrates how metadata can be configured with GCFoundation. In addition to globally-defined metadata information, your application&apos;s metadata can be fully-customized on each page to allow for your application to be fully-optimized for search engines (i.e. SEO)..
        /// </summary>
        public static string Metadata_Description {
            get {
                return ResourceManager.GetString("Metadata_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        public static string Metadata_Examples_Heading {
            get {
                return ResourceManager.GetString("Metadata_Examples_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works.
        /// </summary>
        public static string Metadata_HowItWorks_Heading {
            get {
                return ResourceManager.GetString("Metadata_HowItWorks_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controllers inheriting GCFoundationBaseController can add tags during action execution. The base class exposes them to the view post-action..
        /// </summary>
        public static string Metadata_HowItWorks_Intro {
            get {
                return ResourceManager.GetString("Metadata_HowItWorks_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout rendering and merge.
        /// </summary>
        public static string Metadata_LayoutMerge_Heading {
            get {
                return ResourceManager.GetString("Metadata_LayoutMerge_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The foundation layout merges controller tags with global tags, avoiding duplicates by name or property. Controller tags are rendered first..
        /// </summary>
        public static string Metadata_LayoutMerge_Intro {
            get {
                return ResourceManager.GetString("Metadata_LayoutMerge_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes and gotchas.
        /// </summary>
        public static string Metadata_Notes_Heading {
            get {
                return ResourceManager.GetString("Metadata_Notes_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Base class requirement&lt;/strong&gt;: Controllers must inherit GCFoundationBaseController to use AddMetaTag..
        /// </summary>
        public static string Metadata_Notes_Item_BaseClass {
            get {
                return ResourceManager.GetString("Metadata_Notes_Item_BaseClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Optional section&lt;/strong&gt;: @section Metas { ... } remains available for manual HTML if needed, but is not required..
        /// </summary>
        public static string Metadata_Notes_Item_OptionalSection {
            get {
                return ResourceManager.GetString("Metadata_Notes_Item_OptionalSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Metadata_Overview_Heading {
            get {
                return ResourceManager.GetString("Metadata_Overview_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Base controller support&lt;/strong&gt;: GCFoundationBaseController collects per-page meta tags and exposes them to views via ViewData[&quot;MetaTags&quot;] after each action..
        /// </summary>
        public static string Metadata_Overview_Item_BaseController {
            get {
                return ResourceManager.GetString("Metadata_Overview_Item_BaseController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Configuration&lt;/strong&gt;: GlobalMetaTags in GCFoundationComponentsSettings is a collection of typed MetaTag objects (appsettings.json)..
        /// </summary>
        public static string Metadata_Overview_Item_Configuration {
            get {
                return ResourceManager.GetString("Metadata_Overview_Item_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Layout rendering and merge&lt;/strong&gt;: _FoundationLayout.cshtml merges controller-provided tags with configured global tags, avoiding duplicates by name or property. Controller tags take precedence..
        /// </summary>
        public static string Metadata_Overview_Item_LayoutMerge {
            get {
                return ResourceManager.GetString("Metadata_Overview_Item_LayoutMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Strongly-typed model&lt;/strong&gt;: MetaTag supports name/content, property/content (Open Graph, Twitter), http-equiv/content, charset, and optional English/French strings via &lt;code&gt;contentEn&lt;/code&gt; / &lt;code&gt;contentFr&lt;/code&gt; with &lt;code&gt;content&lt;/code&gt; as fallback..
        /// </summary>
        public static string Metadata_Overview_Item_TypedModel {
            get {
                return ResourceManager.GetString("Metadata_Overview_Item_TypedModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string Metadata_Page_Title {
            get {
                return ResourceManager.GetString("Metadata_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On this page.
        /// </summary>
        public static string Metadata_SideNav_OnThisPage {
            get {
                return ResourceManager.GetString("Metadata_SideNav_OnThisPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage in controllers.
        /// </summary>
        public static string Metadata_Usage_Heading {
            get {
                return ResourceManager.GetString("Metadata_Usage_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherit from GCFoundationBaseController and call AddMetaTag in your action..
        /// </summary>
        public static string Metadata_Usage_Intro {
            get {
                return ResourceManager.GetString("Metadata_Usage_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As part of the GCFoundation, you also get a set of standard translations that you can use in your GCFoundation applications..
        /// </summary>
        public static string Translations_Description {
            get {
                return ResourceManager.GetString("Translations_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use.
        /// </summary>
        public static string Translations_HowToUse_Heading {
            get {
                return ResourceManager.GetString("Translations_HowToUse_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using GCFoundation standard translations is pretty simple. Just make sure that Localization has been configured in your project and, to declare the proper @using statements on your Razor views and you&apos;ll be able to start using standardized translations in your content..
        /// </summary>
        public static string Translations_HowToUse_Intro {
            get {
                return ResourceManager.GetString("Translations_HowToUse_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Translations.
        /// </summary>
        public static string Translations_Page_Title {
            get {
                return ResourceManager.GetString("Translations_Page_Title", resourceCulture);
            }
        }
    }
}
