//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCFoundation.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Navigation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Navigation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GCFoundation.Web.Resources.Navigation", typeof(Navigation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Nav_Authentication {
            get {
                return ResourceManager.GetString("Nav_Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Nav_Authentication_Login {
            get {
                return ResourceManager.GetString("Nav_Authentication_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Nav_Authentication_Logout {
            get {
                return ResourceManager.GetString("Nav_Authentication_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stateless Auth Examples.
        /// </summary>
        public static string Nav_Authentication_StatelessExamples {
            get {
                return ResourceManager.GetString("Nav_Authentication_StatelessExamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components.
        /// </summary>
        public static string Nav_Components {
            get {
                return ResourceManager.GetString("Nav_Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accordion.
        /// </summary>
        public static string Nav_Components_Accordion {
            get {
                return ResourceManager.GetString("Nav_Components_Accordion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Badge.
        /// </summary>
        public static string Nav_Components_Badge {
            get {
                return ResourceManager.GetString("Nav_Components_Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        public static string Nav_Components_Card {
            get {
                return ResourceManager.GetString("Nav_Components_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered Search.
        /// </summary>
        public static string Nav_Components_FilteredSearch {
            get {
                return ResourceManager.GetString("Nav_Components_FilteredSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string Nav_Components_Form {
            get {
                return ResourceManager.GetString("Nav_Components_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Builder.
        /// </summary>
        public static string Nav_Components_FormBuilder {
            get {
                return ResourceManager.GetString("Nav_Components_FormBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GC Design System Components.
        /// </summary>
        public static string Nav_Components_GCDesign {
            get {
                return ResourceManager.GetString("Nav_Components_GCDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCFoundation Components.
        /// </summary>
        public static string Nav_Components_GCFoundation {
            get {
                return ResourceManager.GetString("Nav_Components_GCFoundation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modal.
        /// </summary>
        public static string Nav_Components_Modal {
            get {
                return ResourceManager.GetString("Nav_Components_Modal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Heading.
        /// </summary>
        public static string Nav_Components_PageHeading {
            get {
                return ResourceManager.GetString("Nav_Components_PageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepper.
        /// </summary>
        public static string Nav_Components_Stepper {
            get {
                return ResourceManager.GetString("Nav_Components_Stepper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Nav_Components_Table {
            get {
                return ResourceManager.GetString("Nav_Components_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table (Grid.js).
        /// </summary>
        public static string Nav_Components_TableGridJs {
            get {
                return ResourceManager.GetString("Nav_Components_TableGridJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login Partial.
        /// </summary>
        public static string Nav_Components_UserLogin {
            get {
                return ResourceManager.GetString("Nav_Components_UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string Nav_Errors {
            get {
                return ResourceManager.GetString("Nav_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Error.
        /// </summary>
        public static string Nav_Errors_Global {
            get {
                return ResourceManager.GetString("Nav_Errors_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Not Found.
        /// </summary>
        public static string Nav_Errors_NotFound {
            get {
                return ResourceManager.GetString("Nav_Errors_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string Nav_GetStarted {
            get {
                return ResourceManager.GetString("Nav_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility statement.
        /// </summary>
        public static string Nav_Home_AccessibilityStatement {
            get {
                return ResourceManager.GetString("Nav_Home_AccessibilityStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation.
        /// </summary>
        public static string Nav_Installation {
            get {
                return ResourceManager.GetString("Nav_Installation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Modified/Version Number.
        /// </summary>
        public static string Nav_Installation_DateModified {
            get {
                return ResourceManager.GetString("Nav_Installation_DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Resources.
        /// </summary>
        public static string Nav_Installation_GlobalResources {
            get {
                return ResourceManager.GetString("Nav_Installation_GlobalResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string Nav_Installation_Metadata {
            get {
                return ResourceManager.GetString("Nav_Installation_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Translations.
        /// </summary>
        public static string Nav_Installation_Translations {
            get {
                return ResourceManager.GetString("Nav_Installation_Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Nav_Language {
            get {
                return ResourceManager.GetString("Nav_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        public static string Nav_Styles {
            get {
                return ResourceManager.GetString("Nav_Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Templates.
        /// </summary>
        public static string Nav_Template {
            get {
                return ResourceManager.GetString("Nav_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Page.
        /// </summary>
        public static string Nav_Template_Basic {
            get {
                return ResourceManager.GetString("Nav_Template_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Page Code.
        /// </summary>
        public static string Nav_Template_Basic_Code {
            get {
                return ResourceManager.GetString("Nav_Template_Basic_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Page Demo.
        /// </summary>
        public static string Nav_Template_Basic_Demo {
            get {
                return ResourceManager.GetString("Nav_Template_Basic_Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Page (with Side Navigation) Code.
        /// </summary>
        public static string Nav_Template_Basic_SideNav_Code {
            get {
                return ResourceManager.GetString("Nav_Template_Basic_SideNav_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Page (with Side Navigation) Demo.
        /// </summary>
        public static string Nav_Template_Basic_SideNav_Demo {
            get {
                return ResourceManager.GetString("Nav_Template_Basic_SideNav_Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRUD Pages.
        /// </summary>
        public static string Nav_Template_Crud {
            get {
                return ResourceManager.GetString("Nav_Template_Crud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRUD Page Code.
        /// </summary>
        public static string Nav_Template_Crud_Code {
            get {
                return ResourceManager.GetString("Nav_Template_Crud_Code", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CRUD Page Demo.
        /// </summary>
        public static string Nav_Template_Crud_Demo {
            get {
                return ResourceManager.GetString("Nav_Template_Crud_Demo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dashboard Page.
        /// </summary>
        public static string Nav_Template_Dashboard {
            get {
                return ResourceManager.GetString("Nav_Template_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Page Code.
        /// </summary>
        public static string Nav_Template_Dashboard_Code {
            get {
                return ResourceManager.GetString("Nav_Template_Dashboard_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Page Demo.
        /// </summary>
        public static string Nav_Template_Dashboard_Demo {
            get {
                return ResourceManager.GetString("Nav_Template_Dashboard_Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Page.
        /// </summary>
        public static string Nav_Template_Error {
            get {
                return ResourceManager.GetString("Nav_Template_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Page Code.
        /// </summary>
        public static string Nav_Template_Error_Code {
            get {
                return ResourceManager.GetString("Nav_Template_Error_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Page Demo.
        /// </summary>
        public static string Nav_Template_Error_Demo {
            get {
                return ResourceManager.GetString("Nav_Template_Error_Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Chooser Page.
        /// </summary>
        public static string Nav_Template_LanguageChooser {
            get {
                return ResourceManager.GetString("Nav_Template_LanguageChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Chooser Page Code.
        /// </summary>
        public static string Nav_Template_LanguageChooser_Code {
            get {
                return ResourceManager.GetString("Nav_Template_LanguageChooser_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Chooser Page Demo.
        /// </summary>
        public static string Nav_Template_LanguageChooser_Demo {
            get {
                return ResourceManager.GetString("Nav_Template_LanguageChooser_Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepper Page.
        /// </summary>
        public static string Nav_Template_Stepper {
            get {
                return ResourceManager.GetString("Nav_Template_Stepper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepper Page Code.
        /// </summary>
        public static string Nav_Template_Stepper_Code {
            get {
                return ResourceManager.GetString("Nav_Template_Stepper_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive Examples.
        /// </summary>
        public static string Nav_UserLogin_Examples {
            get {
                return ResourceManager.GetString("Nav_UserLogin_Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Examples.
        /// </summary>
        public static string Nav_UserLogin_Positions {
            get {
                return ResourceManager.GetString("Nav_UserLogin_Positions", resourceCulture);
            }
        }
    }
}
