//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCFoundation.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Template {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Template() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GCFoundation.Web.Resources.Template", typeof(Template).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to basic.
        /// </summary>
        public static string Basic_Anchor {
            get {
                return ResourceManager.GetString("Basic_Anchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;Copy this code to recreate the demo of the basic page template.&lt;/gcds-text&gt;
        ///&lt;gcds-text&gt;&lt;em&gt;Note: most of the work is done through configuration. See the &lt;a href=&quot;{0}&quot;&gt;How to implement&lt;/a&gt; section for details.&lt;/em&gt;&lt;/gcds-text&gt;.
        /// </summary>
        public static string Basic_Code_Intro {
            get {
                return ResourceManager.GetString("Basic_Code_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code of the Basic Page Template.
        /// </summary>
        public static string Basic_Code_Name {
            get {
                return ResourceManager.GetString("Basic_Code_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A basic page template includes the Government of Canada header and footer, H1, H2 and H3 heading sections with text underneath each section..
        /// </summary>
        public static string Basic_Demo_Image_AltText {
            get {
                return ResourceManager.GetString("Basic_Demo_Image_AltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo of the Basic Page Template.
        /// </summary>
        public static string Basic_Demo_Name {
            get {
                return ResourceManager.GetString("Basic_Demo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section {0}.
        /// </summary>
        public static string Basic_Demo_SectionX {
            get {
                return ResourceManager.GetString("Basic_Demo_SectionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of the sub-section.
        /// </summary>
        public static string Basic_Demo_SubSection {
            get {
                return ResourceManager.GetString("Basic_Demo_SubSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your content ends here.
        /// </summary>
        public static string Basic_Demo_YourContentEndsHere {
            get {
                return ResourceManager.GetString("Basic_Demo_YourContentEndsHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your content starts here.
        /// </summary>
        public static string Basic_Demo_YourContentStartsHere {
            get {
                return ResourceManager.GetString("Basic_Demo_YourContentStartsHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to design-considerations-side-nav.
        /// </summary>
        public static string Basic_Design_SideNav_Anchor {
            get {
                return ResourceManager.GetString("Basic_Design_SideNav_Anchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;Copy this code to recreate the demo of the basic page template with a Side Navigation menu.&lt;/gcds-text&gt;
        ///&lt;gcds-text&gt;&lt;em&gt;Note: most of the work is done through configuration. See the &lt;a href=&quot;{0}&quot;&gt;How to implement&lt;/a&gt; section for details.&lt;/em&gt;&lt;/gcds-text&gt;.
        /// </summary>
        public static string Basic_Design_SideNav_Code_Intro {
            get {
                return ResourceManager.GetString("Basic_Design_SideNav_Code_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code of the Basic Page Template (with Side Navigation).
        /// </summary>
        public static string Basic_Design_SideNav_Code_Name {
            get {
                return ResourceManager.GetString("Basic_Design_SideNav_Code_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A basic page template with side navigation includes the Government of Canada header and footer, H1, H2, H3 heading sections with text underneath each section as well as a side navigation menu containing links to each section of this page..
        /// </summary>
        public static string Basic_Design_SideNav_Demo_Image_AltText {
            get {
                return ResourceManager.GetString("Basic_Design_SideNav_Demo_Image_AltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo of the Basic Page Template (with Side Navigation).
        /// </summary>
        public static string Basic_Design_SideNav_Demo_Name {
            get {
                return ResourceManager.GetString("Basic_Design_SideNav_Demo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;list-square&quot;&gt;
        ///&lt;li&gt;Include a side navigation section with bulleted anchor links for pages with four or more sections.&lt;/li&gt;
        ///&lt;li&gt;Anchor links to improve navigation and help people find relevant content.&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string Basic_Design_SideNav_Description {
            get {
                return ResourceManager.GetString("Basic_Design_SideNav_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview &quot;Side Navigation&quot;.
        /// </summary>
        public static string Basic_Design_SideNav_Preview {
            get {
                return ResourceManager.GetString("Basic_Design_SideNav_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to design-considerations-side-nav-preview.
        /// </summary>
        public static string Basic_Design_SideNav_Preview_Anchor {
            get {
                return ResourceManager.GetString("Basic_Design_SideNav_Preview_Anchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improve navigation on longer pages.
        /// </summary>
        public static string Basic_Design_SideNav_Title {
            get {
                return ResourceManager.GetString("Basic_Design_SideNav_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;Getting the basic page template up-and-running is mostly about configuring your application correctly. All you&apos;ll need to do is follow the instructions of the &lt;a href=&quot;{0}&quot;&gt;GCFoundation Installation page&lt;/a&gt;.&lt;/gcds-text&gt;
        ///&lt;gcds-text&gt;This will load to the underlying &lt;code&gt;_FoundationLayout&lt;/code&gt; shared view. Finally, just ensure that you include the following statement in &lt;code&gt;Views/_ViewStart.cshtml&lt;/code&gt; to make the &lt;code&gt;_FoundationLayout&lt;/code&gt; the default page template for your application [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Basic_HowToImplement {
            get {
                return ResourceManager.GetString("Basic_HowToImplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The basic (or default) layout template provides the base structure used across GCFoundation pages. It&apos;s provides accessibility essentials for page structure and heading hierarchy. Brand elements, like the header and footer, make it recognizable as a Government of Canada page..
        /// </summary>
        public static string Basic_Intro {
            get {
                return ResourceManager.GetString("Basic_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Page Template.
        /// </summary>
        public static string Basic_Name {
            get {
                return ResourceManager.GetString("Basic_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;The Basic Page Template is built using the following GCFoundation components that are built off of GC Design System components that meet WCAG 2.1 AA accessibility standards:&lt;/gcds-text&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;&lt;code&gt;&amp;lt;gcds-container&amp;gt;&lt;/code&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;code&gt;&amp;lt;gcds-date-modified&amp;gt;&lt;/code&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;code&gt;&amp;lt;gcds-footer&amp;gt;&lt;/code&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;code&gt;&amp;lt;gcds-header&amp;gt;&lt;/code&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;code&gt;&amp;lt;gcds-heading&amp;gt;&lt;/code&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;code&gt;&amp;lt;gcds-link&amp;gt;&lt;/code&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;code&gt;&amp;lt;gcds-text&amp;gt;&lt;/code&gt;&lt;/li&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Basic_Notes {
            get {
                return ResourceManager.GetString("Basic_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;For use on ASP.Net GC applications.&lt;/gcds-text&gt;
        ///&lt;gcds-text&gt;The basic page template is for non-specialized pages across Canada.ca and is an optional template. It has the starting elements needed for a simple page and those required for most GC pages and applications. You can use it as a canvas to add or combine &lt;a href=&quot;{0}&quot;&gt;components&lt;/a&gt; from GCFoundation (via TagHelpers) and the GC Design System.&lt;/gcds-text&gt;.
        /// </summary>
        public static string Basic_WhenToUse {
            get {
                return ResourceManager.GetString("Basic_WhenToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get code in new tab.
        /// </summary>
        public static string Code_Button {
            get {
                return ResourceManager.GetString("Code_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy template.
        /// </summary>
        public static string CopyTemplate_Button {
            get {
                return ResourceManager.GetString("CopyTemplate_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Crud_Back_Button {
            get {
                return ResourceManager.GetString("Crud_Back_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to employee list.
        /// </summary>
        public static string Crud_BackToEmployeeList_Button {
            get {
                return ResourceManager.GetString("Crud_BackToEmployeeList_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo page.
        /// </summary>
        public static string Crud_Code_Demo_Title {
            get {
                return ResourceManager.GetString("Crud_Code_Demo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an example of what an edit page can look like for a CRUD page..
        /// </summary>
        public static string Crud_Code_Edit_Text {
            get {
                return ResourceManager.GetString("Crud_Code_Edit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo edit page.
        /// </summary>
        public static string Crud_Code_Edit_Title {
            get {
                return ResourceManager.GetString("Crud_Code_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an example of what a view model can look like for a CRUD page to support both form and table display..
        /// </summary>
        public static string Crud_Code_EmployeeViewModel_Text {
            get {
                return ResourceManager.GetString("Crud_Code_EmployeeViewModel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo employee view model.
        /// </summary>
        public static string Crud_Code_EmployeeViewModel_Title {
            get {
                return ResourceManager.GetString("Crud_Code_EmployeeViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;Use the following code to recreate the CRUD page template demo, including the employee view model, employee table, edit form and profile view.&lt;/gcds-text&gt;.
        /// </summary>
        public static string Crud_Code_Intro {
            get {
                return ResourceManager.GetString("Crud_Code_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code for the CRUD page template.
        /// </summary>
        public static string Crud_Code_Name {
            get {
                return ResourceManager.GetString("Crud_Code_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an example of what a view page can look like for a CRUD page..
        /// </summary>
        public static string Crud_Code_Profile_Text {
            get {
                return ResourceManager.GetString("Crud_Code_Profile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo view page.
        /// </summary>
        public static string Crud_Code_Profile_Title {
            get {
                return ResourceManager.GetString("Crud_Code_Profile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add employee.
        /// </summary>
        public static string Crud_Demo_AddEmployee_Button {
            get {
                return ResourceManager.GetString("Crud_Demo_AddEmployee_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Crud_Demo_Address_Label {
            get {
                return ResourceManager.GetString("Crud_Demo_Address_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string Crud_Demo_DateOfBirth_Label {
            get {
                return ResourceManager.GetString("Crud_Demo_DateOfBirth_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete employee.
        /// </summary>
        public static string Crud_Demo_DeleteEmployee_Title {
            get {
                return ResourceManager.GetString("Crud_Demo_DeleteEmployee_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Delete to continue, or Cancel to return to the employee list..
        /// </summary>
        public static string Crud_Demo_DeleteModal_Instruction {
            get {
                return ResourceManager.GetString("Crud_Demo_DeleteModal_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete employee.
        /// </summary>
        public static string Crud_Demo_DeleteModal_Text {
            get {
                return ResourceManager.GetString("Crud_Demo_DeleteModal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete employee?.
        /// </summary>
        public static string Crud_Demo_DeleteModal_Title {
            get {
                return ResourceManager.GetString("Crud_Demo_DeleteModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Crud_Demo_Department_Label {
            get {
                return ResourceManager.GetString("Crud_Demo_Department_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit employee information.
        /// </summary>
        public static string Crud_Demo_EditProfile_Title {
            get {
                return ResourceManager.GetString("Crud_Demo_EditProfile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        public static string Crud_Demo_EmployeeId_Label {
            get {
                return ResourceManager.GetString("Crud_Demo_EmployeeId_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification level.
        /// </summary>
        public static string Crud_Demo_EmployeeLevel_Label {
            get {
                return ResourceManager.GetString("Crud_Demo_EmployeeLevel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string Crud_Demo_EmployeeName_Label {
            get {
                return ResourceManager.GetString("Crud_Demo_EmployeeName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A CRUD page template includes the Government of Canada header and footer, an information notice with an Add employee button, and an employee list table with filter and sort controls, columns for employee ID, full name and classification level, and View, Edit and Delete action buttons for each row..
        /// </summary>
        public static string Crud_Demo_Image_AltText {
            get {
                return ResourceManager.GetString("Crud_Demo_Image_AltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demonstration illustrates the create, read, update and delete (CRUD) operations available in the CRUD page template. The employee records shown are fictitious and serve as an example of the template in use..
        /// </summary>
        public static string Crud_Demo_Intro {
            get {
                return ResourceManager.GetString("Crud_Demo_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager name.
        /// </summary>
        public static string Crud_Demo_ManagerName_Label {
            get {
                return ResourceManager.GetString("Crud_Demo_ManagerName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the button below to access the employee record creation form..
        /// </summary>
        public static string Crud_Demo_Notice_Text {
            get {
                return ResourceManager.GetString("Crud_Demo_Notice_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new employee record.
        /// </summary>
        public static string Crud_Demo_Notice_Title {
            get {
                return ResourceManager.GetString("Crud_Demo_Notice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo of the CRUD page template.
        /// </summary>
        public static string Crud_Demo_PageTitle {
            get {
                return ResourceManager.GetString("Crud_Demo_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Crud_Demo_Salary_Label {
            get {
                return ResourceManager.GetString("Crud_Demo_Salary_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string Crud_Demo_StartDate_Label {
            get {
                return ResourceManager.GetString("Crud_Demo_StartDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee list.
        /// </summary>
        public static string Crud_Demo_TableCaption {
            get {
                return ResourceManager.GetString("Crud_Demo_TableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This table is provided for demonstration purposes only. Data shown is fictitious..
        /// </summary>
        public static string Crud_Demo_TableCaptionDetail {
            get {
                return ResourceManager.GetString("Crud_Demo_TableCaptionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this section to simulate adding, viewing, updating and deleting employee records. Changes are not saved between sessions..
        /// </summary>
        public static string Crud_Demo_TableSectionDescription {
            get {
                return ResourceManager.GetString("Crud_Demo_TableSectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee records.
        /// </summary>
        public static string Crud_Demo_TableSectionTitle {
            get {
                return ResourceManager.GetString("Crud_Demo_TableSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View employee information.
        /// </summary>
        public static string Crud_Demo_ViewProfile_Title {
            get {
                return ResourceManager.GetString("Crud_Demo_ViewProfile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Services.
        /// </summary>
        public static string Crud_Edit_Department_AdministrativeServices {
            get {
                return ResourceManager.GetString("Crud_Edit_Department_AdministrativeServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Development.
        /// </summary>
        public static string Crud_Edit_Department_ApplicationDevelopment {
            get {
                return ResourceManager.GetString("Crud_Edit_Department_ApplicationDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cybersecurity.
        /// </summary>
        public static string Crud_Edit_Department_Cybersecurity {
            get {
                return ResourceManager.GetString("Crud_Edit_Department_Cybersecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise Architecture.
        /// </summary>
        public static string Crud_Edit_Department_EnterpriseArchitecture {
            get {
                return ResourceManager.GetString("Crud_Edit_Department_EnterpriseArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT Operations.
        /// </summary>
        public static string Crud_Edit_Department_ItOperations {
            get {
                return ResourceManager.GetString("Crud_Edit_Department_ItOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT Strategy.
        /// </summary>
        public static string Crud_Edit_Department_ItStrategy {
            get {
                return ResourceManager.GetString("Crud_Edit_Department_ItStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Support.
        /// </summary>
        public static string Crud_Edit_Department_ProgramSupport {
            get {
                return ResourceManager.GetString("Crud_Edit_Department_ProgramSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to David Chen.
        /// </summary>
        public static string Crud_Edit_Manager_DavidChen {
            get {
                return ResourceManager.GetString("Crud_Edit_Manager_DavidChen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karen Wu.
        /// </summary>
        public static string Crud_Edit_Manager_KarenWu {
            get {
                return ResourceManager.GetString("Crud_Edit_Manager_KarenWu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linda Osei.
        /// </summary>
        public static string Crud_Edit_Manager_LindaOsei {
            get {
                return ResourceManager.GetString("Crud_Edit_Manager_LindaOsei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit employee information.
        /// </summary>
        public static string Crud_Edit_PageTitle {
            get {
                return ResourceManager.GetString("Crud_Edit_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;Connect the pages to your application’s data service, replace the sample employee data and configure validation, authorization and audit logging before deployment.&lt;/gcds-text&gt;
        ///&lt;gcds-text&gt;Review the implementation against your organization’s security, privacy and records-management requirements.&lt;/gcds-text&gt;.
        /// </summary>
        public static string Crud_HowToImplement {
            get {
                return ResourceManager.GetString("Crud_HowToImplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CRUD page templates demonstrate common create, read, update and delete tasks for employee records. Use them as a starting point and adapt the fields and workflows to your application’s requirements..
        /// </summary>
        public static string Crud_Intro {
            get {
                return ResourceManager.GetString("Crud_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;abbr title=&quot;Create, Read, Update and Delete&quot;&gt;CRUD&lt;/abbr&gt; Page Templates.
        /// </summary>
        public static string Crud_Name {
            get {
                return ResourceManager.GetString("Crud_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;The demonstration uses in-memory sample data. Changes are not persisted and are reset when the page is reloaded.&lt;/gcds-text&gt;
        ///&lt;gcds-text&gt;Do not use the sample implementation as a production data store.&lt;/gcds-text&gt;.
        /// </summary>
        public static string Crud_Notes {
            get {
                return ResourceManager.GetString("Crud_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View employee information.
        /// </summary>
        public static string Crud_Profile_PageTitle {
            get {
                return ResourceManager.GetString("Crud_Profile_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page is currently under development. Content and functionality may change..
        /// </summary>
        public static string Crud_UnderDevelopment_Text {
            get {
                return ResourceManager.GetString("Crud_UnderDevelopment_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;Use these templates when an authorized user needs to create, view, update or delete structured records in a Government of Canada web application.&lt;/gcds-text&gt;
        ///&lt;gcds-text&gt;Adapt the templates to the program’s business rules, privacy requirements and user needs before implementation.&lt;/gcds-text&gt;.
        /// </summary>
        public static string Crud_WhenToUse {
            get {
                return ResourceManager.GetString("Crud_WhenToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;(...)&lt;/gcds-text&gt;.
        /// </summary>
        public static string Dashboard_HowToImplement {
            get {
                return ResourceManager.GetString("Dashboard_HowToImplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;(...)&lt;/gcds-text&gt;.
        /// </summary>
        public static string Dashboard_Intro {
            get {
                return ResourceManager.GetString("Dashboard_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Page Template.
        /// </summary>
        public static string Dashboard_Name {
            get {
                return ResourceManager.GetString("Dashboard_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;(...)&lt;/gcds-text&gt;.
        /// </summary>
        public static string Dashboard_Notes {
            get {
                return ResourceManager.GetString("Dashboard_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;For use on ASP.Net GC applications.&lt;/gcds-text&gt;
        ///&lt;gcds-text&gt;(...)&lt;/gcds-text&gt;.
        /// </summary>
        public static string Dashboard_WhenToUse {
            get {
                return ResourceManager.GetString("Dashboard_WhenToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open demo in new tab.
        /// </summary>
        public static string Demo_Button {
            get {
                return ResourceManager.GetString("Demo_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design considerations.
        /// </summary>
        public static string DesignConsiderations {
            get {
                return ResourceManager.GetString("DesignConsiderations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to design-considerations.
        /// </summary>
        public static string DesignConsiderations_Anchor {
            get {
                return ResourceManager.GetString("DesignConsiderations_Anchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to basic.
        /// </summary>
        public static string Error_Anchor {
            get {
                return ResourceManager.GetString("Error_Anchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;Copy this code to recreate the demo of the error page template.&lt;/gcds-text&gt;.
        /// </summary>
        public static string Error_Code_Intro {
            get {
                return ResourceManager.GetString("Error_Code_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code of the Error Page Template.
        /// </summary>
        public static string Error_Code_Name {
            get {
                return ResourceManager.GetString("Error_Code_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error page template includes the Government of Canada header and footer, a notice explaining what went wrong, a link for the user to provide feedback as well as a link to redirect the user to a safe location..
        /// </summary>
        public static string Error_Demo_Image_AltText {
            get {
                return ResourceManager.GetString("Error_Demo_Image_AltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo of the Error Page Template.
        /// </summary>
        public static string Error_Demo_Name {
            get {
                return ResourceManager.GetString("Error_Demo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;Instead of creating your own error pages, you can use GCFoundation&apos;s built-in error pages. The following sample pages are available to use:&lt;/gcds-text&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;&lt;gcds-link href=&quot;{0}&quot; target=&quot;_blank&quot;&gt;Global error&lt;/gcds-link&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;gcds-link href=&quot;{1}&quot; target=&quot;_blank&quot;&gt;Page not found error&lt;/gcds-link&gt;&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;gcds-text&gt;Enable it application-wide by wiring error handling by using the &lt;code&gt;app.UseExceptionHandler(&quot;{0}&quot;)&lt;/code&gt; and &lt;code&gt;app.UseStatusCodePagesWithReExecute(&quot;{1}&quot;)&lt;/code&gt; s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Error_Design_UseBuiltIn_Description {
            get {
                return ResourceManager.GetString("Error_Design_UseBuiltIn_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use built-in error pages.
        /// </summary>
        public static string Error_Design_UseBuiltIn_Title {
            get {
                return ResourceManager.GetString("Error_Design_UseBuiltIn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;Use this template to build simple, bilingual error pages:&lt;/gcds-text&gt;
        ///&lt;ul class=&quot;list-square&quot;&gt;
        ///&lt;li&gt;Set &lt;code&gt;Layout = &quot;_BilingualErrorTemplate&quot;&lt;/code&gt; in your error view.&lt;/li&gt;
        ///&lt;li&gt;Add a page title and a &lt;code&gt;&amp;lt;gcds-notice notice-role=&quot;danger&quot;&amp;gt;&lt;/code&gt; component with helpful next steps (feedback and a safe link).&lt;/li&gt;
        ///&lt;li&gt;Enable it application-wide by wiring error handling per the &lt;a href=&quot;{0}&quot;&gt;GCFoundation installation page&lt;/a&gt;: &lt;code&gt;UseExceptionHandler(&quot;{{your-url}}&quot;)&lt;/code&gt;.&lt;/li&gt;
        ///&lt;/u [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Error_HowToImplement {
            get {
                return ResourceManager.GetString("Error_HowToImplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;The GCFoundation framework provides you with an error page template that can be customized to deliver the message you want to send your users when they hit a road-block.&lt;/gcds-text&gt;
        ///&lt;gcds-text&gt;The framework also includes two (2) error pages out-of-the-box. Refer to the &lt;gcds-link href=&quot;{0}&quot;&gt;{1}&lt;/gcds-link&gt; section for more information. These packaged error pages can be configured to gracefully handle any unhandled exceptions thrown by your application.&lt;/gcds-text&gt;
        ///.
        /// </summary>
        public static string Error_Intro {
            get {
                return ResourceManager.GetString("Error_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Page Template.
        /// </summary>
        public static string Error_Name {
            get {
                return ResourceManager.GetString("Error_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;For use on ASP.Net GC applications.&lt;/gcds-text&gt;
        ///&lt;gcds-text&gt;The error page template is designed to display a generic message to users when the application throws an error or when the user tries to perform an invalid operation. It is a lightweight version of the basic page template and its sole purpose is to redirect the user to a safe location. It has the basic elements of a GC page as well as a &lt;code&gt;&amp;lt;gcds-notice&amp;gt;&lt;/code&gt; component explaining what went wrong, a link for the user to provide  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Error_WhenToUse {
            get {
                return ResourceManager.GetString("Error_WhenToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to implement.
        /// </summary>
        public static string HowToImplement {
            get {
                return ResourceManager.GetString("HowToImplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how-to-implement.
        /// </summary>
        public static string HowToImplement_Anchor {
            get {
                return ResourceManager.GetString("HowToImplement_Anchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A generic page layout including the necessary components for any accessible GC pages.
        /// </summary>
        public static string Index_Basic_Description {
            get {
                return ResourceManager.GetString("Index_Basic_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Page.
        /// </summary>
        public static string Index_Basic_Title {
            get {
                return ResourceManager.GetString("Index_Basic_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will update this list of page templates as we develop them..
        /// </summary>
        public static string Index_Browse_Description {
            get {
                return ResourceManager.GetString("Index_Browse_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse templates.
        /// </summary>
        public static string Index_Browse_Title {
            get {
                return ResourceManager.GetString("Index_Browse_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collection of page templates for the implementation of standard &lt;abbr title=&quot;Create, Read, Update and Delete&quot;&gt;CRUD&lt;/abbr&gt; operations.
        /// </summary>
        public static string Index_Crud_Description {
            get {
                return ResourceManager.GetString("Index_Crud_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRUD Pages.
        /// </summary>
        public static string Index_Crud_Title {
            get {
                return ResourceManager.GetString("Index_Crud_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of a dashboard page template.
        /// </summary>
        public static string Index_Dashboard_Description {
            get {
                return ResourceManager.GetString("Index_Dashboard_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Page.
        /// </summary>
        public static string Index_Dashboard_Title {
            get {
                return ResourceManager.GetString("Index_Dashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardize the display and the handling of errors thrown by your application.
        /// </summary>
        public static string Index_Error_Description {
            get {
                return ResourceManager.GetString("Index_Error_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Page.
        /// </summary>
        public static string Index_Error_Title {
            get {
                return ResourceManager.GetString("Index_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bilingual splash page similar to the one used on Canada.ca.
        /// </summary>
        public static string Index_LanguageChooser_Description {
            get {
                return ResourceManager.GetString("Index_LanguageChooser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Chooser Page.
        /// </summary>
        public static string Index_LanguageChooser_Title {
            get {
                return ResourceManager.GetString("Index_LanguageChooser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn about the page templates included in the GCFoundation framework. Page templates are pre-built pages that combine GCFoundation and GC Design System components for common presentations. They’re fully responsive for multi-device use. Their page structures support a predictable, recognizable, and accessible user experience..
        /// </summary>
        public static string Index_PageDescription {
            get {
                return ResourceManager.GetString("Index_PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Templates.
        /// </summary>
        public static string Index_PageTitle {
            get {
                return ResourceManager.GetString("Index_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let users track their progress within a multi-page form.
        /// </summary>
        public static string Index_Stepper_Description {
            get {
                return ResourceManager.GetString("Index_Stepper_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepper Page.
        /// </summary>
        public static string Index_Stepper_Title {
            get {
                return ResourceManager.GetString("Index_Stepper_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under development.
        /// </summary>
        public static string Index_Template_UnderDevelopment {
            get {
                return ResourceManager.GetString("Index_Template_UnderDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;Copy this code to recreate the language chooser page template.&lt;/gcds-text&gt;.
        /// </summary>
        public static string LanguageChooser_Code_Intro {
            get {
                return ResourceManager.GetString("LanguageChooser_Code_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code of the Language Chooser Page Template.
        /// </summary>
        public static string LanguageChooser_Code_Name {
            get {
                return ResourceManager.GetString("LanguageChooser_Code_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A language chooser page template displays the Government of Canada signature, English and French language buttons side by side, and the Canada wordmark at the bottom..
        /// </summary>
        public static string LanguageChooser_Demo_Image_AltText {
            get {
                return ResourceManager.GetString("LanguageChooser_Demo_Image_AltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo of the Language Chooser Page Template.
        /// </summary>
        public static string LanguageChooser_Demo_Name {
            get {
                return ResourceManager.GetString("LanguageChooser_Demo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;To use this template:&lt;/gcds-text&gt;
        ///&lt;ul class=&quot;list-square&quot;&gt;
        ///&lt;li&gt;Create a controller action that returns the &lt;code&gt;~/Views/Language/Index.cshtml&lt;/code&gt; view from GCFoundation.Components.&lt;/li&gt;
        ///&lt;li&gt;Pass a &lt;code&gt;LanguageChooserModel&lt;/code&gt; with your application titles and language-specific URLs.&lt;/li&gt;
        ///&lt;li&gt;The view automatically applies the &lt;code&gt;LanguageChooserPage.min.css&lt;/code&gt; stylesheet.&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;gcds-text&gt;For full setup instructions, see the &lt;a href=&quot;{0}&quot;&gt;GCFoundation Installation page&lt;/a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LanguageChooser_HowToImplement {
            get {
                return ResourceManager.GetString("LanguageChooser_HowToImplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;GCFoundation provides a ready-to-use language chooser page template that mirrors the Canada.ca splash page. It displays the Government of Canada signature, English and French language buttons, and an optional terms and conditions link.&lt;/gcds-text&gt;
        ///&lt;gcds-text&gt;The template includes a random background image feature and is fully responsive for mobile devices.&lt;/gcds-text&gt;.
        /// </summary>
        public static string LanguageChooser_Intro {
            get {
                return ResourceManager.GetString("LanguageChooser_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Chooser Page Template.
        /// </summary>
        public static string LanguageChooser_Name {
            get {
                return ResourceManager.GetString("LanguageChooser_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;The Language Chooser Page Template uses the following GCFoundation and GC Design System components:&lt;/gcds-text&gt;
        ///&lt;ul class=&quot;list-square&quot;&gt;
        ///&lt;li&gt;&lt;code&gt;&amp;lt;gcds-signature&amp;gt;&lt;/code&gt; - Government of Canada signature&lt;/li&gt;
        ///&lt;li&gt;&lt;code&gt;&amp;lt;gcds-button&amp;gt;&lt;/code&gt; - Language selection buttons&lt;/li&gt;
        ///&lt;li&gt;&lt;code&gt;&amp;lt;gcds-grid&amp;gt;&lt;/code&gt; - Responsive layout&lt;/li&gt;
        ///&lt;/ul&gt;
        ///&lt;gcds-text&gt;The template stores background images in &lt;code&gt;wwwroot/images/splash/&lt;/code&gt; and randomly selects one on each page load.&lt;/gcds-text&gt;.
        /// </summary>
        public static string LanguageChooser_Notes {
            get {
                return ResourceManager.GetString("LanguageChooser_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot coming soon..
        /// </summary>
        public static string LanguageChooser_Screenshot_Placeholder {
            get {
                return ResourceManager.GetString("LanguageChooser_Screenshot_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;For use on ASP.Net GC applications.&lt;/gcds-text&gt;
        ///&lt;gcds-text&gt;The language chooser page template is the bilingual splash page users see before entering your application. It lets visitors select their preferred official language (English or French) while meeting Government of Canada accessibility and bilingualism requirements.&lt;/gcds-text&gt;.
        /// </summary>
        public static string LanguageChooser_WhenToUse {
            get {
                return ResourceManager.GetString("LanguageChooser_WhenToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notes.
        /// </summary>
        public static string Notes_Anchor {
            get {
                return ResourceManager.GetString("Notes_Anchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preview.
        /// </summary>
        public static string Preview_Anchor {
            get {
                return ResourceManager.GetString("Preview_Anchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Foundation includes two error templates:.
        /// </summary>
        public static string Section_ErrorTemplates_Description {
            get {
                return ResourceManager.GetString("Section_ErrorTemplates_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error templates.
        /// </summary>
        public static string Section_ErrorTemplates_Title {
            get {
                return ResourceManager.GetString("Section_ErrorTemplates_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bilingual splash page similar to the one used on Canada.ca..
        /// </summary>
        public static string Section_LanguageChooser_Description {
            get {
                return ResourceManager.GetString("Section_LanguageChooser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language chooser template.
        /// </summary>
        public static string Section_LanguageChooser_Title {
            get {
                return ResourceManager.GetString("Section_LanguageChooser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main layout template provides the base structure used across pages..
        /// </summary>
        public static string Section_MainTemplate_Description {
            get {
                return ResourceManager.GetString("Section_MainTemplate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main template.
        /// </summary>
        public static string Section_MainTemplate_Title {
            get {
                return ResourceManager.GetString("Section_MainTemplate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A configurable, bilingual component for displaying user authentication information. Supports stateless authentication systems perfect for Azure cloud deployments..
        /// </summary>
        public static string Section_UserLoginPartial_Description {
            get {
                return ResourceManager.GetString("Section_UserLoginPartial_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User login partial template.
        /// </summary>
        public static string Section_UserLoginPartial_Title {
            get {
                return ResourceManager.GetString("Section_UserLoginPartial_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error templates.
        /// </summary>
        public static string SideNav_ErrorTemplates {
            get {
                return ResourceManager.GetString("SideNav_ErrorTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On this page.
        /// </summary>
        public static string SideNav_Label {
            get {
                return ResourceManager.GetString("SideNav_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language chooser template.
        /// </summary>
        public static string SideNav_LanguageChooser {
            get {
                return ResourceManager.GetString("SideNav_LanguageChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main template.
        /// </summary>
        public static string SideNav_MainTemplate {
            get {
                return ResourceManager.GetString("SideNav_MainTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User login partial.
        /// </summary>
        public static string SideNav_UserLoginPartial {
            get {
                return ResourceManager.GetString("SideNav_UserLoginPartial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;Copy this code to recreate the demo of the stepper page template.&lt;/gcds-text&gt;.
        /// </summary>
        public static string Stepper_Code_Intro {
            get {
                return ResourceManager.GetString("Stepper_Code_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code of the Stepper Page Template.
        /// </summary>
        public static string Stepper_Code_Name {
            get {
                return ResourceManager.GetString("Stepper_Code_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Stepper_Demo_ContactOptions_Email {
            get {
                return ResourceManager.GetString("Stepper_Demo_ContactOptions_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose one or more ways we can contact you.
        /// </summary>
        public static string Stepper_Demo_ContactOptions_Hint {
            get {
                return ResourceManager.GetString("Stepper_Demo_ContactOptions_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact options.
        /// </summary>
        public static string Stepper_Demo_ContactOptions_Label {
            get {
                return ResourceManager.GetString("Stepper_Demo_ContactOptions_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        public static string Stepper_Demo_ContactOptions_Sms {
            get {
                return ResourceManager.GetString("Stepper_Demo_ContactOptions_Sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your first name.
        /// </summary>
        public static string Stepper_Demo_FirstName_Hint {
            get {
                return ResourceManager.GetString("Stepper_Demo_FirstName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Stepper_Demo_FirstName_Label {
            get {
                return ResourceManager.GetString("Stepper_Demo_FirstName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A stepper page template includes the Government of Canada header and footer, a GCFoundation stepper component and a GCFoundation form (or form builder) component..
        /// </summary>
        public static string Stepper_Demo_Image_AltText {
            get {
                return ResourceManager.GetString("Stepper_Demo_Image_AltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your last name.
        /// </summary>
        public static string Stepper_Demo_LastName_Hint {
            get {
                return ResourceManager.GetString("Stepper_Demo_LastName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Stepper_Demo_LastName_Label {
            get {
                return ResourceManager.GetString("Stepper_Demo_LastName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo of the Stepper Page Template.
        /// </summary>
        public static string Stepper_Demo_Name {
            get {
                return ResourceManager.GetString("Stepper_Demo_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Review the information you entered before submitting.
        /// </summary>
        public static string Stepper_Demo_Review_Intro {
            get {
                return ResourceManager.GetString("Stepper_Demo_Review_Intro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter your first name.
        /// </summary>
        public static string Stepper_Demo_FirstName_Required {
            get {
                return ResourceManager.GetString("Stepper_Demo_FirstName_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter your last name.
        /// </summary>
        public static string Stepper_Demo_LastName_Required {
            get {
                return ResourceManager.GetString("Stepper_Demo_LastName_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter a short biography about yourself.
        /// </summary>
        public static string Stepper_Demo_Bio_Required {
            get {
                return ResourceManager.GetString("Stepper_Demo_Bio_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Biography must be at least 10 characters.
        /// </summary>
        public static string Stepper_Demo_Bio_MinLength {
            get {
                return ResourceManager.GetString("Stepper_Demo_Bio_MinLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Biography cannot exceed 2000 characters.
        /// </summary>
        public static string Stepper_Demo_Bio_MaxLength {
            get {
                return ResourceManager.GetString("Stepper_Demo_Bio_MaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select your country of residence.
        /// </summary>
        public static string Stepper_Demo_Country_Required {
            get {
                return ResourceManager.GetString("Stepper_Demo_Country_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select your gender.
        /// </summary>
        public static string Stepper_Demo_Gender_Required {
            get {
                return ResourceManager.GetString("Stepper_Demo_Gender_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Stepper_Demo_Website_Label {
            get {
                return ResourceManager.GetString("Stepper_Demo_Website_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter a website such as example.com, www.example.com, or https://example.com.
        /// </summary>
        public static string Stepper_Demo_Website_Required {
            get {
                return ResourceManager.GetString("Stepper_Demo_Website_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter a valid website such as example.com, www.example.com, or https://example.com.
        /// </summary>
        public static string Stepper_Demo_Website_Invalid {
            get {
                return ResourceManager.GetString("Stepper_Demo_Website_Invalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Accepts example.com, www.example.com, http://…, or https://….
        /// </summary>
        public static string Stepper_Demo_Website_Hint {
            get {
                return ResourceManager.GetString("Stepper_Demo_Website_Hint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter your age.
        /// </summary>
        public static string Stepper_Demo_Age_Required {
            get {
                return ResourceManager.GetString("Stepper_Demo_Age_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Age must be a number between 18 and 100.
        /// </summary>
        public static string Stepper_Demo_Age_Range {
            get {
                return ResourceManager.GetString("Stepper_Demo_Age_Range", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You must agree to the terms and conditions to continue.
        /// </summary>
        public static string Stepper_Demo_AgreeToTerms_Required {
            get {
                return ResourceManager.GetString("Stepper_Demo_AgreeToTerms_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Submission successful.
        /// </summary>
        public static string Stepper_Demo_Success_Title {
            get {
                return ResourceManager.GetString("Stepper_Demo_Success_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your information has been submitted successfully. This is a demonstration only; no data was saved.
        /// </summary>
        public static string Stepper_Demo_Success_Message {
            get {
                return ResourceManager.GetString("Stepper_Demo_Success_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start over.
        /// </summary>
        public static string Stepper_Demo_Success_StartOver {
            get {
                return ResourceManager.GetString("Stepper_Demo_Success_StartOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alberta.
        /// </summary>
        public static string Stepper_Demo_Province_Alberta {
            get {
                return ResourceManager.GetString("Stepper_Demo_Province_Alberta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British Columbia.
        /// </summary>
        public static string Stepper_Demo_Province_BritishColumbia {
            get {
                return ResourceManager.GetString("Stepper_Demo_Province_BritishColumbia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province or territory.
        /// </summary>
        public static string Stepper_Demo_Province_Label {
            get {
                return ResourceManager.GetString("Stepper_Demo_Province_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontario.
        /// </summary>
        public static string Stepper_Demo_Province_Ontario {
            get {
                return ResourceManager.GetString("Stepper_Demo_Province_Ontario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quebec.
        /// </summary>
        public static string Stepper_Demo_Province_Quebec {
            get {
                return ResourceManager.GetString("Stepper_Demo_Province_Quebec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro.
        /// </summary>
        public static string Stepper_Demo_Step1_Label {
            get {
                return ResourceManager.GetString("Stepper_Demo_Step1_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Stepper_Demo_Step2_Label {
            get {
                return ResourceManager.GetString("Stepper_Demo_Step2_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Stepper_Demo_Step3_Label {
            get {
                return ResourceManager.GetString("Stepper_Demo_Step3_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Stepper_Demo_Step4_Label {
            get {
                return ResourceManager.GetString("Stepper_Demo_Step4_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Stepper_Demo_Step5_Label {
            get {
                return ResourceManager.GetString("Stepper_Demo_Step5_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;gcds-text&gt;Add a stepper and a simple form as shown in the demo. Refer to the &lt;gcds-link href=&quot;{0}&quot;&gt;Components&lt;/gcds-link&gt; documentation for more specific instructions.&lt;/gcds-text&gt;.
        /// </summary>
        public static string Stepper_HowToImplement {
            get {
                return ResourceManager.GetString("Stepper_HowToImplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A page template including a step indicator and a simple form for short multi-step flows..
        /// </summary>
        public static string Stepper_Intro {
            get {
                return ResourceManager.GetString("Stepper_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepper Page Template.
        /// </summary>
        public static string Stepper_Name {
            get {
                return ResourceManager.GetString("Stepper_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;list-square&quot;&gt;
        ///&lt;li&gt;Keep steps concise.&lt;/li&gt;
        ///&lt;li&gt;Use GCFoundation components to develop the form to ensure validation and other features are included.&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string Stepper_Notes {
            get {
                return ResourceManager.GetString("Stepper_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use when guiding users through a short multi-step process with clear progress..
        /// </summary>
        public static string Stepper_WhenToUse {
            get {
                return ResourceManager.GetString("Stepper_WhenToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When to use.
        /// </summary>
        public static string WhenToUse {
            get {
                return ResourceManager.GetString("WhenToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when-to-use.
        /// </summary>
        public static string WhenToUse_Anchor {
            get {
                return ResourceManager.GetString("WhenToUse_Anchor", resourceCulture);
            }
        }
    }
}
